const symbols = {
    adzcoin: 'ADZ',
    'auroracoin-qubit': 'AUR',
    bitcoin: 'BTC',
    'bitcoin-cash': 'BCH',
    'bitcoin-gold': 'BTG',
    dash: 'DASH',
    'digibyte-groestl': 'DGB',
    'digibyte-quebit': 'DGB',
    'digibyte-skein': 'DGB',
    electroneum: 'ETN',
    ethereum: 'ETH',
    'ethereum-classic': 'ETC',
    expanse: 'EXP',
    feathercoin: 'FTC',
    gamecredits: 'GAME',
    geocoin: 'GEO',
    globalboosty: 'BSTY',
    groestlcoin: 'GRS',
    litecoin: 'LTC',
    maxcoin: 'MAX',
    monacoin: 'MONA',
    monero: 'XMR',
    musicoin: 'MUSIC',
    'myriadcoin-groestl': 'XMY',
    'myriadcoin-skein': 'XMY',
    'myriadcoin-yescript': 'XMY',
    sexcoin: 'SXC',
    siacoin: 'SC',
    startcoin: 'START',
    'verge-scrypt': 'XVG',
    vertcoin: 'VTC',
    zcash: 'ZEC',
    zclassic: 'ZCL',
    zcoin: 'XZC',
    zencash: 'ZEN',
};

export default symbols;